name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setup
        run: script/setup
      - name: Build Application
        run: script/build_frontend
      - name: Zip static files
        run: zip -r frontend-master.zip hass_frontend
      - name: Sending static files
        run: curl -s -u ${{ secrets.USER }}:${{ secrets.PASSWORD }} -X POST https://api.bitbucket.org/2.0/repositories/unisec/unicontrol/downloads -F files=@frontend-master.zip
